# Generated by Django 4.0.2 on 2022-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itrrequest',
            name='form16',
            field=models.ImageField(blank=True, default='NA', upload_to=''),
        ),
    ]
