# Generated by Django 4.0.2 on 2022-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_itrrequest_form16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itrrequest',
            name='form16',
            field=models.FileField(blank=True, default='NA', upload_to=''),
        ),
    ]
